baseURL = 'https://haidarali.net/'
languageCode = 'en-us'
title = 'Haidar Ali'
theme = "tufte-custom"
defaultContentLanguage = "en"
copyright = "CC BY 4.0"

[params]
    # subtitle = "Software Engineer"
    pronunciation = "hay-th-er aa-lee"
    showPoweredBy = false
    copyright = "CC BY 4.0"
    codeBlocksDark = true
    sansSubtitle = false
    github = "haidar47x"
    linkedin = "haidar47x"
    email = "haidar47x@gmail.com"
    rss = true
    showSummary = false
    math = false
    main_page = "about"
    centerArticle = true

[menu]

    [[menu.nav]]
        name = "Blog"
        weight = -100
        identifier = "posts"
        url = "/posts/"

    [[menu.nav]]
        name = "Open-Source"
        weight = -90
        identifier = "projects"
        url = "/projects"

    [[ menu.nav ]]
        name = "About"
        weight = -80
        identifier = "about"
        url = "/"

[pagintion]
    paperSize = 3