baseURL = 'https://haidarali.net/'
languageCode = 'en-us'
title = 'Haidar Ali'
theme = "hugo-tufte"
defaultContentLanguage = "en"
copyright = "CC BY 4.0"

[params]
    subtitle = "Software Engineer"
    showPoweredBy = false
    copyrightHolder = "Haidar Ali"
    codeBlocksDark = true
    sansSubtitle = false

    github = "haidar47x"
    linkedin = "haidar47x"
    email = "haidar47x@gmail.com"
    rss = true
    showSummary = false
    math = false
    centerArticle = true

[menu]
  [[menu.nav]]
    name = "About"
    weight = -110
    identifier = "about"
    url = "/"

  [[menu.nav]]
    name = "Posts"
    weight = -100
    identifier = "posts"
    url = "/posts/"

  [[menu.nav]]
    name = "Open-Source"
    weight = -90
    identifier = "projects"
    url = "/projects"

[pagintion]
    paperSize = 3